<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>asynchronous-selfcheck18</title>
    <style>
    body {
      background-color: tan;
      margin: 0;
      font-family: Verdana, sans-serif;
    }

    .title {
      color: red;
      text-align: center;
      font-weight:700;
    }

    .task{
      width: 52%;
      padding: 15px 25px;
      color: navy;
      background-color: #e2e2e2;
      margin: 35px auto;
    }

    .code-ex {
      width: 60%;
      font-family: sans-serif;
      background-color: #bebebe;
      font-size: large;
      padding-left: 15px;
      margin: 0 auto;
    }

    p {
      width: 80%;
      margin: 0 auto;
    }
    </style>
</head>
<body>

    <h2 class="title">Асинхронний код, самоперевірка</h2>

    <h4 class="task">Подивіться на код, який приведено нижче, проаналізуйте його.<br>
      Що буде викликатись раніше та що буде виведено в консолі?<br>
      А як зробити навпаки, покажіть рішення?
    </h4>
    <br>

    <p class="code-ex">
      <code>
        <br>
        'use strict';<br>
        <br>
        &nbsp;let promise = new Promise((resolve, reject) => {<br>
        &nbsp;&nbsp;setTimeout(() => reject(new Error("error")), 1000);<br>
        &nbsp;&nbsp;setTimeout(() => resolve("ignored"), 2000);<br>
        &nbsp;});<br>
        <br>
        &nbsp;promise<br>
        &nbsp;&nbsp;.then(<br>
        &nbsp;&nbsp;&nbsp;&nbsp;result => console.log("Fulfilled: " + result),<br>
        &nbsp;&nbsp;&nbsp;&nbsp;error => console.log("Rejected: " + error)<br>
        &nbsp;&nbsp;);<br>
        <br>
      </code>
    </p>
    <br>

    <script>
      'use strict';

      let promise = new Promise((resolve, reject) => {
        setTimeout(() => reject(new Error("error")), 1000);
        setTimeout(() => resolve("ignored"), 2000);
      });
      
      promise
        .then(
          result => console.log("Fulfilled: " + result),
          error => console.log("Rejected: " + error)
        );
    </script>

    <p><b>Рішення:</b></p>
    <br>

    <p>Перше, що необхідно сказати це те, що проміс переходить тільки в один стан - той що визначений в коді першим.
      У нашому випадку це стан <i>"reject"</i>. Коли проміс перейшов або у стан <i>"виконано"</i> з результатом 
      <i>"resolve"</i> чи в стан <i>"відхилено"</i> з результатом <i>"reject"</i> то це назавжди.<br>
      Після виклику <i>"resolve/reject"</i> проміс вже не може <i>"передумати"</i>.<br>
    </p><br>
    
    <p>А отже, в результаті виклику цього коду спрацює тільки перший обробник <i>"then"</i> бо після
      виклику <i>"reject"</i> проміс вже отримав стан з помилкою, і в подальшому його вже нічого не змінить.
      Наступні виклики <i>"resolve/reject"</i> будуть просто ігноруватись.<br>
      Тому <i>"setTimeout"</i> із затримкою 1 секунду - виконається з результатом: <i>"error"</i> і в консоль 
      першим буде виведено <i>"Rejected: error"</i><br>
      А той <i>"setTimeout"</i> із затримкою в 2 секунди, буде проігнорований.
    </p>

    <p>А так – навпаки, стан <i>"resolve"</i>' буде першим:</p>
    <br>


    <p class="code-ex">
      <code>
        <br>
        'use strict';<br>
        <br>
        let promise = new Promise((resolve, reject) => {<br>
        <br>
        &nbsp;setTimeout(() => resolve('result'), 1000); // через 1 секунду буде результат: <i>'result'</i><br>
        <br>
        &nbsp;setTimeout(() => reject(new Error('ignored')), 2000); // стан <i>'reject'</i> буде проігнорований<br>
        });<br>
        <br>
        &nbsp;promise<br>
        &nbsp;&nbsp;.then(<br>
        &nbsp;&nbsp;&nbsp;result => console.log("Fulfilled: " + result), // обробник спрацює<br>
        &nbsp;&nbsp;&nbsp;error => console.log("Rejected: " + error) // обробник не буде працювати<br>
        &nbsp;&nbsp;);<br>
        <br>
        </code>
    </p>
    <br>
    <br>
    <br>
  </body>

</html>